#cloud-config

users:
  - name: zach
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCudWw3jiJI90peXnoxQV3IDdmXpHdxNVUb6R1bUK42G3sXs89hAv7h3v6cH0GSgFLqRflqwvqiFgXk0nGKAVAxE+zKS06kLgx0/Lidcf7VmQxXrJhEO5X5cLMyvUey7AuvBtSRgJrJy6BMJ8vp5oCctlme3tjxwK80SQ+5ZBJbG0v8eB6E3szsu6rVNGsIcOxUKLAU/HryZbZRMeT8us71xeccmecMEpnM93rS9bv4muf70uuhl2cxs3LllOIx9l1bpRp29NPilACenlKFpFiAvSs8vyJLbmm+uT8bLE93YPLh+iQPXgrSSOiMcdZ421mw5yrpoj0hPGGMUKFw5JXg5G5XzhpS2NcncGd8Zxknw+BNYb/KulWaItnPYG/bBmru8He8jCo8sxaYSrXCrOPLqVOFBwyp5Tl4qcqliAuXulcyDXH2NhLCNnLYlH0IQvxoOzJZZVDO8gawLXoE0I+OfAY5ZFdR4flbVmhTEQ5BJHdvYILxXlz/lbQ5c3697Ik=
    groups: ['sudo']
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
locale: en_US.UTF-8
timezone: US/East
apt:
  sources:
    tailscale.list:
      source: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
      # curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | gpg --show-keys
      keyid: 2596A99EAAB33821893C0A79458CA832957F5868
package_update: true
package_upgrade: true
packages:
  - tailscale

write_files:
  - content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.forwarding=1
    path: /etc/sysctl.d/99-tailscale.conf
    permissions: '0644'


runcmd:
  - sysctl -p /etc/sysctl.d/99-tailscale.conf
  - tailscale up --advertise-exit-node --authkey ${tailscale_auth_key}